language: objective-c
osx_image: xcode9.1
cache:
  directories:
  - Carthage
before_install:
- openssl aes-256-cbc -K $encrypted_ad15086dbf75_key -iv $encrypted_ad15086dbf75_iv
  -in SaldoEMT/Resources/Secrets.plist.enc -out SaldoEMT/Resources/Secrets.plist -d
- openssl aes-256-cbc -K $encrypted_ad15086dbf75_key -iv $encrypted_ad15086dbf75_iv
  -in fastlane/metadata.tar.enc -out fastlane/metadata.tar -d
- gem install fastlane --no-rdoc --no-ri --no-document --quiet
script:
- fastlane test
env:
  global:
  - secure: lklWqJ/XzDSGYeogj+i3LsUcyZHNkU1kwTbSBgGXZ+zu5LBIiPOh6sZTKl4AbBOwzQXjx/zMRtGFT9+U3hvjkAw0MYtCEQ+MMC7o0UAJkwyLACbg8qK2YKnruYM2+iNtyBej2S8id3TnwYq9y41E5esmC45h7qfBBteepqZk3wLDiIiVGdoRIil27jlG+CvbAlcIqWcTo7zSlj2HxDdQEXQKb+EtpMduQItjxIR5RjrM/xnFnhsP9g0YkwmwoFwaNVfuwjiuuat825fJBbrBMiQIv86Fq4Wd1TjuNxCHKp8rKz588aLIHpxjA3JmsqPsVEDI/7rDXvQyejx03p898wZQUqHl6OQgoadK8y/3/TwvU69pdrLWdgRGhRjtC1iuhDQOienD23WWzdCMwWNPBocOmvqGspyxaBJmKSsZU5rteUhlwLNOFlTVr2mmetq4rmIudPf+apqRE1GdxKlcINhdRIsWkCsJq8b+tsVuzL78OgfYWAyQOlRXNRhIPkoVX3vvTg7u9JkkH76Rtw6/Yg4CdBdnbvbcbl5sXOmxbSewZAhbIAjkZCbCcCNKcknw7BSpOHJerN12wcnoglhj/lVkVYcO00lTkI5aDAnpOplJDZo7LppNK0V7jw8uyUGqhv0p8g+4ph4CmojE0jAopU/Tq6s5CEcLn9kjMLQuoew=
  - secure: IkrEV8WbhI9Bh60UKlB//F6u6GqpMK1wCgEHVn+ndDwh79ZEovu4x+SnMmcQx4I/KFHw6EpCL+YFi4lDq75zOt1xpMosdim8WViMiDSD0GUXliMIUe7hHQ/4WE/bBYZQalB2tfQxuD3B29Q//kJdhCrNIQwyoddTtCnMl8PodGBctlfYX2ERZ+Zi0grj0BTg5lG6f8nUS3VJw1sah6FaRXwscg7k3NveeG7B4jKEQ9Zx6P/gLvhz00YRTJ441HbNiaZUPkwfUhkmqgQD7IRZUXZrzXaghDhNU1639Ceeukivd8FB/FcRFQP00TjWYTzoQWhJAcY1NPgCWNm+Xi/1MANMALaACz8wpjvzBPZ4x7/New82Y2SeDTf5X5mCL5Us882cgJKc2NrRr35ga/kNEXviJaIKb3kRwwSqlWCZd0tjro+AHG/wOdJ2hFMSNTVzRA509YLXwhcD0kFS4y9D3jekHZiGh5bhZSnRcjzkZqWTE3mrmSU3k//lwvGVQvGev8hMTZ1LMWX5S7ks8H8S/oy2nBOhT7r8pY1/g5XWiSGv8eHnlB3hPmfRpQcGuAmCCLP17ITg3qGPB5H7lGHFxEhojuSGAfK2XNSpHBRdA6Fh/bepKjbxixhpHWvQQ9j+6jq98fTJ5/kn7egtw9JNLohGnk7vjGYJTKaOTYdHhic=
