devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone 5s",
  "iPhone X"
])

languages([
  "en-GB",
  "es-ES"
])

scheme "Screenshots"

clear_previous_screenshots true
erase_simulator true
reinstall_app true